/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 5.7.20-log : Database - bbf_log
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`bbf_log` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `bbf_log`;

/*Table structure for table `admin_account_modify_log_tb` */

DROP TABLE IF EXISTS `admin_account_modify_log_tb`;

CREATE TABLE `admin_account_modify_log_tb` (
  `seq` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '번호',
  `ptn_month` TINYINT(4) NOT NULL COMMENT '파티셔닝 키',
  `log_time` INT(11) NOT NULL,
  `member_id` VARCHAR(20) NOT NULL COMMENT '유저아이디',
  `user_id` BIGINT(20) NOT NULL COMMENT '유저아이디',
  `nickname` VARCHAR(25) DEFAULT NULL COMMENT '닉네임',
  `level` INTEGER(11) NOT NULL DEFAULT 0 COMMENT '레벨',
  `exp` INTEGER(11) NOT NULL DEFAULT 0 COMMENT '계정 경험치',
  `rank_point` INTEGER(11) NOT NULL DEFAULT 0 COMMENT '랭킹 포인트',
  `tier` INTEGER(11) NOT NULL DEFAULT 0 COMMENT '랭킹 티어',
  `vip` TINYINT(4) NOT NULL DEFAULT 0 COMMENT 'vip 레벨',
  `grade` CHAR(1) NOT NULL DEFAULT 0 COMMENT '등급',
  `wallet` VARCHAR(255) DEFAULT NULL COMMENT '메타마스크 지갑 주소',
  
  `reg_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초 생성 시간',
  PRIMARY KEY (`seq`,`ptn_month`)
  ) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4
/*!50100 PARTITION BY LIST (ptn_month)
(PARTITION p1 VALUES IN (1) ENGINE = InnoDB,
 PARTITION p2 VALUES IN (2) ENGINE = InnoDB,
 PARTITION p3 VALUES IN (3) ENGINE = InnoDB,
 PARTITION p4 VALUES IN (4) ENGINE = InnoDB,
 PARTITION p5 VALUES IN (5) ENGINE = InnoDB,
 PARTITION p6 VALUES IN (6) ENGINE = InnoDB,
 PARTITION p7 VALUES IN (7) ENGINE = InnoDB,
 PARTITION p8 VALUES IN (8) ENGINE = InnoDB,
 PARTITION p9 VALUES IN (9) ENGINE = InnoDB,
 PARTITION p10 VALUES IN (10) ENGINE = InnoDB,
 PARTITION p11 VALUES IN (11) ENGINE = InnoDB,
 PARTITION p12 VALUES IN (12) ENGINE = InnoDB) */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
